### ISSUE TITLE
运行test.py遇到的问题

### ISSUE THREAD

**Issue by push-xiting** [xdFai/SCTransNet#17]
![807396de0857e1623ca1aad05073f2f2](https://github.com/user-attachments/assets/2b338b91-16eb-4a94-bd47-ffad7220320f)
输入数据与模型类型不一致 这个改怎么解决呢

**Comment by xdFai** [comment]
同学你好，这个应该是网络模型和输入的图像不在设备的同一个位置，
你可以尝试将模型和图像后面都加上 .cuda() 来确保都在GPU上运行。




袁帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdFai/SCTransNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 下午4:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xdFai/SCTransNet] 运行test.py遇到的问题 (Issue #17)





 
807396de0857e1623ca1aad05073f2f2.png (view on web)
 输入数据与模型类型不一致 这个改怎么解决呢
