### ISSUE TITLE
关于论文中的可视化结果

### ISSUE THREAD

**Issue by bobo66597** [xdFai/SCTransNet#18]
作者您好，非常感谢你在红外弱小目标检测领域做出的贡献，我是该方向的初学者，我想请教一下论文中的，各个解码阶段的注意力可视化图是如何绘制的，用什么应用绘制的？
![1731643491660](https://github.com/user-attachments/assets/87ea9dc4-d5f7-4de9-94b9-3074aed64367)

**Comment by xdFai** [comment]
同学您好，感谢您对文章的关注，注意力可视化图 我参考的GradCAM，你可以参考下这个帖子，代码整体还是比较好修改的。
https://blog.csdn.net/leviopku/article/details/124629151




袁帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdFai/SCTransNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 中午12:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xdFai/SCTransNet] 关于论文中的可视化结果 (Issue #18)





 
作者您好，非常感谢你在红外弱小目标检测领域做出的贡献，我是该方向的初学者，我想请教一下论文中的，各个解码阶段的注意力可视化图是如何绘制的，用什么应用绘制的？
 1731643491660.png (view on web)

**Comment by bobo66597** [comment]
> 同学您好，感谢您对文章的关注，注意力可视化图 我参考的GradCAM，你可以参考下这个帖子，代码整体还是比较好修改的。 https://blog.csdn.net/leviopku/article/details/124629151 袁帅 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人： “xdFai/SCTransNet” ***@***.***>; 发送时间：&nbsp;2024年11月15日(星期五) 中午12:17 @***.***>; @***.***>; 主题：&nbsp;[xdFai/SCTransNet] 关于论文中的可视化结果 （Issue #18） 作者您好，非常感谢你在红外弱小目标检测领域做出的贡献，我是该方向的初学者，我想请教一下论文中的，各个解码阶段的注意力可视化图是如何绘制的，用什么应用绘制的？ 1731643491660.png （在 Web 上查看） — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

非常感谢您的回复
