### ISSUE TITLE
过拟合？

### ISSUE THREAD

**Issue by LWTvickyzz** [xdFai/SCTransNet#4]
[NUAA-SIRST_SCTransNet_Sat_May_25_20_41_55_2024.txt](https://github.com/xdFai/SCTransNet/files/15443988/NUAA-SIRST_SCTransNet_Sat_May_25_20_41_55_2024.txt)
您好，按照代码中的相关参数进行训练，只调整了部分参数，如图，我观察到训练日志中，从500轮验证开始到结束，相关的指标一直为0，请问是否是过拟合引起的？期待您的回复
![image](https://github.com/xdFai/SCTransNet/assets/35456947/19b7024c-9b09-4ff6-87b5-44bf3ff3e182)

**Comment by xdFai** [comment]
之前训练的时候 确实没有出现过这种情况  有可能是数据太少的原因  毕竟 NUAA-SIRST 提供训练的数据只有 200+
你可以尝试直接使用SIRST3  更多的数据应该会使得训练的结果更稳定

**Comment by LWTvickyzz** [comment]
好的，感谢。我又试了NUDT和IRSTD-1k，没出现这种情况
