### ISSUE TITLE
IRSTD-1K experiments 

### ISSUE THREAD

**Issue by feifeiwei** [xdFai/SCTransNet#5]
"Thank you for your nice work. The result I obtained from training on the IRSTD-1K dataset is different from that in the paper. Do you have any suggestions to help reproduce it？ thanks!

## here is my result:
[IRSTD-1K_SCTransNet_Fri_Jun__7_21_33_28_2024.txt](https://github.com/user-attachments/files/15781571/IRSTD-1K_SCTransNet_Fri_Jun__7_21_33_28_2024.txt)

**Comment by xdFai** [comment]
Thanks your attention to this work. 
The results presented in this method, as well as in other compare methods are obtained by training on three combined datasets. 
Therefore, I provide only one weight for these three datasets. 
Training on independent datasets may result in some metrics being raised or lowered.

**Comment by feifeiwei** [comment]
Thanks, i will have a try!
